import { useState } from 'react'
import { useAuth } from '../AuthProvider'

function Toggle({ enabled, onChange, label, hint }) { return <div className="settings-row"><div><strong>{label}</strong><p>{hint}</p></div><button className={`settings-toggle ${enabled ? 'on' : ''}`} onClick={() => onChange(!enabled)} aria-pressed={enabled} aria-label={label}><span /></button></div> }

export default function Settings({ theme, onToggleTheme }) {
  const { user } = useAuth()
  const [emailUpdates, setEmailUpdates] = useState(true)
  const [reminders, setReminders] = useState(true)
  return <div className="settings-page"><header className="workspace-page-header"><span className="cp-eyebrow">Account</span><h1>Settings</h1><p>Control how CareerPilot supports your search.</p></header><div className="settings-layout"><aside className="settings-nav"><a href="#profile">Profile</a><a href="#preferences">Preferences</a><a href="#notifications">Notifications</a><a href="#privacy">Privacy</a></aside><div className="settings-panels"><section id="profile" className="settings-panel"><div className="panel-title"><div><h2>Profile</h2><p>Your account details and career context.</p></div><button className="secondary-button">Edit profile</button></div><div className="profile-summary"><span className="settings-avatar">{(user?.email || 'CP').slice(0, 2).toUpperCase()}</span><div><strong>{user?.email?.split('@')[0] || 'CareerPilot member'}</strong><p>{user?.email || 'Add an email address'}</p></div></div></section><section id="preferences" className="settings-panel"><div className="panel-title"><div><h2>Appearance</h2><p>Make your workspace comfortable for long focus sessions.</p></div></div><div className="settings-row"><div><strong>Color theme</strong><p>Switch between the light and dark product themes.</p></div><button className="secondary-button" onClick={onToggleTheme}>{theme === 'dark' ? 'Use light' : 'Use dark'}</button></div></section><section id="notifications" className="settings-panel"><div className="panel-title"><div><h2>Notifications</h2><p>Choose the reminders that help you follow through.</p></div></div><Toggle label="Application reminders" hint="Get reminded when it is time to follow up." enabled={reminders} onChange={setReminders} /><Toggle label="Weekly career digest" hint="A short, useful summary of your job-search activity." enabled={emailUpdates} onChange={setEmailUpdates} /></section><section id="privacy" className="settings-panel"><div className="panel-title"><div><h2>Privacy</h2><p>Your resume content is used only to provide your workspace features.</p></div></div><div className="settings-row"><div><strong>Export your data</strong><p>Download your saved resume and application records.</p></div><button className="secondary-button">Request export</button></div></section></div></div></div>
}
